2024-12-16 09:10:24,366 (124436/MainThread) litecli.main ERROR - sql: 'create table(\nid integer,\nhero_name text\n);', error: OperationalError('near "(": syntax error')
2024-12-16 09:10:24,368 (124436/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/sqlexecute.py", line 123, in run\n    for result in special.execute(cur, sql):\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/packages/special/main.py", line 107, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/main.py", line 438, in one_iteration\n    for title, cur, headers, status in res:\n                                       ^^^\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/sqlexecute.py", line 130, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near "(": syntax error\n'
2024-12-16 09:11:23,243 (124436/MainThread) litecli.main ERROR - sql: 'create table superheroes(\nid integer,\nhero_name text,\n);', error: OperationalError('near ")": syntax error')
2024-12-16 09:11:23,244 (124436/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/sqlexecute.py", line 123, in run\n    for result in special.execute(cur, sql):\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/packages/special/main.py", line 107, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/main.py", line 438, in one_iteration\n    for title, cur, headers, status in res:\n                                       ^^^\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/sqlexecute.py", line 130, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near ")": syntax error\n'
