2024-12-16 09:10:24,366 (124436/MainThread) litecli.main ERROR - sql: 'create table(\nid integer,\nhero_name text\n);', error: OperationalError('near "(": syntax error')
2024-12-16 09:10:24,368 (124436/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/sqlexecute.py", line 123, in run\n    for result in special.execute(cur, sql):\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/packages/special/main.py", line 107, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/main.py", line 438, in one_iteration\n    for title, cur, headers, status in res:\n                                       ^^^\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/sqlexecute.py", line 130, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near "(": syntax error\n'
2024-12-16 09:11:23,243 (124436/MainThread) litecli.main ERROR - sql: 'create table superheroes(\nid integer,\nhero_name text,\n);', error: OperationalError('near ")": syntax error')
2024-12-16 09:11:23,244 (124436/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/sqlexecute.py", line 123, in run\n    for result in special.execute(cur, sql):\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/packages/special/main.py", line 107, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/main.py", line 438, in one_iteration\n    for title, cur, headers, status in res:\n                                       ^^^\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/sqlexecute.py", line 130, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near ")": syntax error\n'
2024-12-16 12:14:23,276 (9904/MainThread) litecli.main ERROR - sql: 'create table my_strict_table(\nfav_num integer,\nuser_name string) strict;', error: OperationalError('unknown datatype for my_strict_table.user_name: "string"')
2024-12-16 12:14:23,278 (9904/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/sqlexecute.py", line 123, in run\n    for result in special.execute(cur, sql):\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/packages/special/main.py", line 107, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/main.py", line 438, in one_iteration\n    for title, cur, headers, status in res:\n                                       ^^^\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/sqlexecute.py", line 130, in run\n    cur.execute(sql)\nsqlite3.OperationalError: unknown datatype for my_strict_table.user_name: "string"\n'
2024-12-16 14:11:04,935 (9904/MainThread) litecli.main ERROR - sql: "insert into villains values \n(1, 'Mag')\n(2, 'Zen');", error: OperationalError('near "(": syntax error')
2024-12-16 14:11:04,936 (9904/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/sqlexecute.py", line 123, in run\n    for result in special.execute(cur, sql):\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/packages/special/main.py", line 107, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/main.py", line 438, in one_iteration\n    for title, cur, headers, status in res:\n                                       ^^^\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/sqlexecute.py", line 130, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near "(": syntax error\n'
2024-12-16 14:11:50,010 (9904/MainThread) litecli.main ERROR - sql: "insert into villains values (\n(1, 'Mag')\n(2, 'Zen')\n) strict;", error: OperationalError('near "(": syntax error')
2024-12-16 14:11:50,011 (9904/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/sqlexecute.py", line 123, in run\n    for result in special.execute(cur, sql):\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/packages/special/main.py", line 107, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/main.py", line 438, in one_iteration\n    for title, cur, headers, status in res:\n                                       ^^^\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/sqlexecute.py", line 130, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near "(": syntax error\n'
2024-12-16 14:13:10,510 (9904/MainThread) litecli.main ERROR - sql: "insert into villains values \n(1, 'Mag'),\n(2, 'Zen') strict;", error: OperationalError('near "strict": syntax error')
2024-12-16 14:13:10,511 (9904/MainThread) litecli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/sqlexecute.py", line 123, in run\n    for result in special.execute(cur, sql):\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/packages/special/main.py", line 107, in execute\n    raise CommandNotFound\nlitecli.packages.special.main.CommandNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/main.py", line 438, in one_iteration\n    for title, cur, headers, status in res:\n                                       ^^^\n  File "/nix/store/j03xhy6wnifdb2n31psck947xzmlr3r6-litecli-1.12.3/lib/python3.12/site-packages/litecli/sqlexecute.py", line 130, in run\n    cur.execute(sql)\nsqlite3.OperationalError: near "strict": syntax error\n'
